const stringifyValue = (value) => (value == null || value === '' ? '' : String(value))
const yn = (value) => (value ? 'Y' : 'N')
const includesOption = (values, option) => (values || []).map(String).includes(String(option))

export function buildSashSavePayload({ form, itgEstiNo, wEstiNo, estiNos = '1', editEstiSeq = '' }) {
  const bfMillingType = stringifyValue(form.bfMillingType || '0')

  return {
    itgEstiNo,
    estiNo: wEstiNo,
    estiNos,
    estiSeq: editEstiSeq || '',

    mdlCd: form.mdlCd,
    wintydiCd: form.wintydiCd,
    bftydiCd: form.bftydiCd,
    sizCd: form.sizCd,
    bsmfOrdUtmCd: form.bsmfOrdUtmCd,
    sashOrdTypCd: form.sashOrdTypCd,
    ctgrCd: 'P',
    windLocCd: '01',
    rt: 1,
    glasDblYn: 'Y',
    unpAplScn: '01',
    m2Unp: '0',

    w0Size: stringifyValue(form.w),
    h0Size: stringifyValue(form.h),
    wSize: stringifyValue(form.w),
    hSize: stringifyValue(form.h),
    qty: stringifyValue(form.qty),
    w1Size: stringifyValue(form.w1),
    w2Size: stringifyValue(form.w2),
    w3Size: stringifyValue(form.w3),
    w4Size: stringifyValue(form.w4),
    w5Size: stringifyValue(form.w5),
    h1Size: stringifyValue(form.h1),
    h2Size: stringifyValue(form.h2),
    h3Size: stringifyValue(form.h3),
    h4Size: stringifyValue(form.h4),
    h5Size: stringifyValue(form.h5),
    csSize: stringifyValue(form.cs),
    cs1Size: stringifyValue(form.cs1),
    cs2Size: stringifyValue(form.cs2),
    cs3Size: stringifyValue(form.cs3),
    cs4Size: stringifyValue(form.cs4),
    cs5Size: stringifyValue(form.cs5),

    crtnColrCd: 'WH',
    insdColrCd: form.insdColrCd,
    ousdColrCd: form.ousdColrCd || form.insdColrCd,

    insdSf: form.insdSf,
    ousdSf: form.ousdSf,
    ventLoc: form.ventLoc || '',
    screenType: form.screenType,
    aluMfYn: form.isAluMf ? 'Y' : 'N',
    aluMfHandleType: form.isAluMf ? stringifyValue(form.aluMfHandleType) : '',
    aluMfMdlYn: form.isAluMf ? stringifyValue(form.aluMfMdlYn || 'Y') : 'N',
    aluMfHndlH: form.isAluMf && form.aluMfMdlYn !== 'Y' ? stringifyValue(form.aluMfHndlH) : '',
    bfSlcnFnshYn: form.slcnFnshYn ? 'Y' : 'N',
    drnHoleYn: yn(form.drnHoleYn),
    ventHoleYn: yn(form.ventHoleYn),
    bfMillingType,
    bfArmatureType: stringifyValue(form.bfArmatureType),
    bfLockCnt: stringifyValue(form.bfLockCnt),
    bfWrapping: stringifyValue(form.bfWrapping),
    bfThrSidePack: stringifyValue(form.bfThrSidePack),
    bfMillingDetail: bfMillingType !== '0' ? stringifyValue(form.bfMillingDetail) : '',
    bfMillingUp: bfMillingType !== '0' ? yn(form.bfMillingUp) : 'N',
    bfMillingDown: bfMillingType !== '0' ? yn(form.bfMillingDown) : 'N',
    bfMillingLeft: bfMillingType !== '0' ? yn(form.bfMillingLeft) : 'N',
    bfMillingRight: bfMillingType !== '0' ? yn(form.bfMillingRight) : 'N',
    bfWeldNoneYn: yn(form.bfWeldNoneYn),
    bfWeld: yn(form.bfWeld),
    fillingPiecesYn: yn(form.fillingPiecesYn),
    bfRackShip: yn(form.bfRackShip),
    bfStopper: yn(form.bfStopper),
    bfDirectShip: yn(form.bfDirectShip),
    bfShipAddr: form.bfDirectShip ? stringifyValue(form.bfShipAddr) : '',
    bfForesidePack: yn(form.bfForesidePackYn),
    bfKsmark: yn(form.bfKsmarkYn),
    bfLxHiddenOptYn: yn(form.bfLxHiddenOptYn),
    bfSideView: stringifyValue(form.bfSideView),
    bfFmGbYn: yn(form.bfFmGbYn),
    bfFmGbShipYn: yn(form.bfFmGbShipYn),
    bfFmGbUpDownYn: yn(form.bfFmGbUpDownYn),
    bfFmGbRlYn: yn(form.bfFmGbRlYn),
    bfFmGbCutYn: yn(form.bfFmGbCutYn),
    bfSsOpt: yn(form.bfSsOpt),
    bfFixBuild: yn(form.bfFixBuild),
    bfFdHd: yn(form.bfFdHd),
    bfTurnDoorPullType: stringifyValue(form.bfTurnDoorPullType),
    bfTurnDoorOneSideWrapType: stringifyValue(form.bfTurnDoorOneSideWrapType),
    bfOneSideWrapColrNm: form.bfTurnDoorOneSideWrapType ? stringifyValue(form.bfOneSideWrapColrNm) : '',
    bfAptCmType: stringifyValue(form.bfAptCmType),
    bfApt1pjMethod: stringifyValue(form.bfApt1pjMethod),
    bfApt2pjLoc: stringifyValue(form.bfApt2pjLoc),
    bfApt2pjMethod: stringifyValue(form.bfApt2pjMethod),
    bfTurnDoorOnlyMakeYn: yn(form.bfTurnDoorOnlyMakeYn),
    bfVentPiecesIncludeYn: yn(form.bfVentPiecesIncludeYn),
    bfWinOnefixUpHoleYn: yn(form.bfWinOnefixUpHoleYn),
    bfWinFmThreeSideYn: yn(form.bfWinFmThreeSideYn),
    bfWinTopBottomFmYn: yn(form.bfWinTopBottomFmYn),
    bfWinSpDdlnShpmYn: yn(form.bfWinSpDdlnShpmYn),
    bfIhyFixHghtDirYn: yn(form.bfIhyFixHghtDirYn),
    sfLandscape: yn(form.sfLandscape),
    sfOppositeTypeYn: yn(form.sfOppositeTypeYn),
    sfRackShip: yn(form.sfRackShip),
    sfDirectShip: yn(form.sfDirectShip),
    sfShipAddr: form.sfDirectShip ? stringifyValue(form.sfShipAddr) : '',
    sfOutGlasYn: yn(form.sfOutGlasYn),
    sfOutGlasInfo: form.sfOutGlasYn ? stringifyValue(form.sfOutGlasInfo) : '',
    sfRoller: stringifyValue(form.sfRoller),
    sfCreHook: yn(form.sfCreHook),
    sfCreSize: stringifyValue(form.sfCreSize),
    sfOutType: stringifyValue(form.sfOutType),
    sfOutType0: stringifyValue(form.sfOutType0),
    sfOutType1: stringifyValue(form.sfOutType1),
    sfOutType2: stringifyValue(form.sfOutType2),
    sfOutType3: stringifyValue(form.sfOutType3),
    sfSontaLoca: stringifyValue(form.sfSontaLoca),
    insdDeckNoneYn: yn(includesOption(form.deco1, 1)),
    ousdDeckNoneYn: yn(includesOption(form.deco1, 2)),
    insd2FDeckNoneYn: yn(includesOption(form.deco1, 3)),
    ousd2FDeckNoneYn: yn(includesOption(form.deco1, 4)),
    insdWindClsYn: yn(includesOption(form.winCloser, 1)),
    ousdWindClsYn: yn(includesOption(form.winCloser, 2)),
    mfRackShip: yn(form.mfRackShip),
    mfCi4wStickYn: yn(form.mfCi4wStickYn),
    mfDirectShip: yn(form.mfDirectShip),
    mfShipAddr: form.mfDirectShip ? stringifyValue(form.mfShipAddr) : '',
    mfHandle: stringifyValue(form.mfHandle),
    mfHandleHsize: form.mfHandle ? stringifyValue(form.mfHandleHsize) : '',
    mfAptArmatureType: stringifyValue(form.mfAptArmatureType),
    glasStdalYn: form.alGlass ? 'Y' : 'N',
    glasAdmsYn: form.glasAdmsYn || 'Y',

    insdHandleType: form.insdHandleType,
    ousdHandleType: form.ousdHandleType,
    insdHndlHMiddle: yn(form.insdHndlHEnabled),
    insdHndlH: form.insdHndlHEnabled ? stringifyValue(form.insdHndlH) : '',
    insd2FHndlHMiddle: yn(form.secondFloorEnabled && form.ousdHndlHEnabled),
    ousdHndlH: form.secondFloorEnabled && form.ousdHndlHEnabled ? stringifyValue(form.ousdHndlH) : '',

    insdBrcktHMiddle: yn(form.insdBrcktHEnabled),
    insdBrcktH: form.insdBrcktHEnabled ? stringifyValue(form.insdBrcktH) : '',
    insd2FBrcktHMiddle: yn(form.secondFloorEnabled && form.ousdBrcktHEnabled),
    ousdBrcktH: form.insdBrcktHEnabled ? stringifyValue(form.ousdBrcktH) : '',
    insd2FBrcktH: form.secondFloorEnabled && form.ousdBrcktHEnabled ? stringifyValue(form.insd2FBrcktH) : '',
    ousd2FBrcktH: form.secondFloorEnabled && form.ousdBrcktHEnabled ? stringifyValue(form.ousd2FBrcktH) : '',

    mtrlCds1: stringifyValue(form.mtrlCds1),
    mtrlCds2: stringifyValue(form.mtrlCds2),
    mtrlCds3: stringifyValue(form.mtrlCds3),
    mtrlCds4: stringifyValue(form.mtrlCds4),
    insdSfGlasMtrlCd: stringifyValue(form.mtrlCds1),
    ousdSfGlasMtrlCd: stringifyValue(form.mtrlCds2),
    insdBfGlasMtrlCd: stringifyValue(form.mtrlCds3),
    ousdBfGlasMtrlCd: stringifyValue(form.mtrlCds4),

    remSrc: form.remSrc,
  }
}
